const form = document.querySelector('#evaluation-form');
const nav = document.querySelector('#section-nav');
const $ = (s, p = document) => p.querySelector(s);
const esc = (v) => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const textField = (id, label, type = 'text', required = false) => `<div class="field"><label for="${id}">${label}</label><input class="input" id="${id}" name="${id}" type="${type}" ${required ? 'required' : ''}></div>`;
const area = (id, label, required = false) => `<div class="field"><label for="${id}">${label}</label><textarea id="${id}" name="${id}" ${required ? 'required' : ''}></textarea></div>`;
const choices = (id, options, type = 'radio') => `<div class="choices">${options.map((o,i)=>`<label class="choice ${type==='checkbox'?'check':''}"><input type="${type}" name="${id}${type==='checkbox'?'[]':''}" value="${esc(o)}"><span>${esc(o)}</span></label>`).join('')}</div>`;
const group = (title, content) => `<div class="subgroup"><div class="group-title">${title}</div>${content}</div>`;
const section = (number, title, body) => `<section class="card" id="s${number}"><div class="card-heading"><span class="section-number">${number}</span><h3>${title}</h3></div><div class="card-body">${body}</div></section>`;
const options = {
  referral:['Médico','Paciente','Google','Instagram','Indicação','Outro'], start:['Súbito','Gradual','Traumático','Sem causa aparente'], duration:['< 6 sem (agudo)','6–12 sem (subagudo)','> 12 sem (crônico)'], evolution:['Melhorando','Estável','Piorando'], side:['Direito','Esquerdo','Bilateral','Central'], painType:['Constante','Intermitente','Variável'], temporal:['Pior de manhã','Pior à tarde','Pior à noite','Sem padrão','Piora ao longo do dia'], characteristics:['Peso','Pontada','Fisgada','Queimação','Choque','Formigamento','Rigidez','Dormência'], worse:['Sentar','Levantar','Flexão','Extensão','Caminhar','Ficar em pé','Deitar','Tosse / espirro'], better:['Caminhar','Movimento','Repouso','Mudar posição','Flexão','Extensão','Medicação','Deitar'], redFlags:['História prévia de câncer','Perda de peso inexplicável','Trauma importante recente','Febre ou infecção recente','Uso prolongado de corticoides','Dor intensa em repouso ou noturna','Fraqueza progressiva em MMII','Anestesia em sela','Alteração urinária ou intestinal recente','Idade > 50 ou < 20 com dor nova']
};
const scale = (id,label) => `<div class="scale"><span class="group-title">${label}</span>${choices(id,[0,1,2,3,4,5,6,7,8,9,10])}</div>`;
const startItems=['A minha dor nas costas se espalhou pelas pernas nas últimas duas semanas.','Eu tive dor no ombro e/ou na nuca pelo menos uma vez nas últimas duas semanas.','Eu evito andar longas distâncias por causa da minha dor nas costas.','Nas duas últimas semanas, tenho me vestido mais devagar por causa da minha dor nas costas.','A atividade física não é realmente segura para uma pessoa com um problema como o meu.','Tenho ficado preocupado por muito tempo por causa da minha dor nas costas.','Eu sinto que minha dor nas costas é terrível e que nunca vai melhorar.','Em geral, eu não tenho gostado de todas as coisas como eu costumava gostar.'];
const roland=['Fico em casa a maior parte do tempo por causa de minhas costas.','Mudo de posição frequentemente tentando deixar minhas costas confortáveis.','Ando mais devagar que o habitual por causa de minhas costas.','Por causa de minhas costas eu não estou fazendo nenhum dos meus trabalhos que geralmente faço em casa.','Por causa de minhas costas, eu uso o corrimão para subir escadas.','Por causa de minhas costas, eu me deito para descansar mais frequentemente.','Por causa de minhas costas, eu tenho que me apoiar em alguma coisa para me levantar de uma cadeira normal.','Por causa de minhas costas, tento conseguir com que outras pessoas façam as coisas por mim.','Eu me visto mais lentamente que o habitual por causa de minhas costas.','Eu somente fico em pé por períodos curtos de tempo por causa de minhas costas.','Por causa de minhas costas evito me abaixar ou ajoelhar.','Encontro dificuldades em me levantar de uma cadeira por causa de minhas costas.','As minhas costas doem quase que todo o tempo.','Tenho dificuldade em me virar na cama por causa das minhas costas.','Meu apetite não é muito bom por causa das dores em minhas costas.','Tenho problemas para colocar minhas meias por causa das dores em minhas costas.','Caminho apenas curtas distâncias por causa de minhas dores nas costas.','Não durmo tão bem por causa de minhas costas.','Por causa de minhas dores nas costas, eu me visto com ajuda de outras pessoas.','Fico sentado a maior parte do dia por causa de minhas costas.','Evito trabalhos pesados em casa por causa de minhas costas.','Por causa das dores em minhas costas, fico mais irritado e mal humorado com as pessoas do que o habitual.','Por causa de minhas costas, eu subo escadas mais vagarosamente do que o habitual.','Fico na cama a maior parte do tempo por causa de minhas costas.'];
const refs=['World Health Organization. WHO guideline for non-surgical management of chronic primary low back pain in adults in primary and community care settings. Geneva: World Health Organization; 2023.','Roland M, Morris R. A study of the natural history of back pain. Part I: Development of a reliable and sensitive measure of disability in low-back pain. Spine. 1983;8(2):141–144.','George SZ et al. Interventions for the Management of Acute and Chronic Low Back Pain: Revision 2021. J Orthop Sports Phys Ther. 2021;51(11):CPG1–CPG60. doi:10.2519/jospt.2021.0304.','Bouhassira D et al. Comparison of pain syndromes associated with nervous or somatic lesion and development of a new neuropathic pain diagnostic questionnaire (DN4). Pain. 2005;114(1–2):29–36.','Hartvigsen J et al. What low back pain is and why we need to pay attention. Lancet. 2018;391(10137):2356–2367. doi:10.1016/S0140-6736(18)30480-X.','Stratford P et al. Assessing disability and change on individual patients: a report of a patient specific measure. Physiother Can. 1995;47:258–263.','Kosek E et al. Chronic nociplastic pain affecting the musculoskeletal system: clinical criteria and grading system. PAIN. 2021;162:2629–2634.','Pillastrini P et al. An updated overview of clinical guidelines for chronic low back pain management in primary care. Joint Bone Spine. 2012;79(2):176–185.','Foster NE et al. Prevention and treatment of low back pain: evidence, challenges, and promising directions. Lancet. 2018;391(10137):2368–2383. doi:10.1016/S0140-6736(18)30489-6.','OMS. Classificação Internacional de Funcionalidade, Incapacidade e Saúde (CIF). Genebra: OMS; 2001.','Hill JC et al. A primary care back pain screening tool: identifying patient subgroups for initial treatment. Arthritis Rheum. 2008;59(5):632–641.','Hodges PW et al. Toward Validation of Clinical Measures to Discriminate Between Nociceptive, Neuropathic, and Nociplastic Pain. Clin J Pain. 2025;41:e1281.'];
const bodyMapState = BodyMap.createState();
const map = view => BodyMap.render(view === 'Frente' ? 'front' : 'back');
const content = [
 [1,'Identificação',`<div class="grid grid-3">${textField('patientName','Nome','text',true)}${textField('birthDate','Data de Nasc.','date')}${textField('age','Idade','number')} ${group('Sexo',choices('sex',['M','F']))}${textField('assessmentDate','Data da Avaliação','date',true)}${textField('profession','Profissão')}${textField('phone','Telefone','tel')}${textField('painDuration','Tempo de dor')}${textField('evaluator','Avaliador')}</div>${group('Encaminhamento',choices('referral',options.referral,'checkbox'))}`],
 [2,'Queixa Principal',area('chiefComplaint','Queixa Principal',true)],
 [3,'História da Condição',`${group('Início',choices('onset',options.start))}${group('Tempo de Evolução',choices('duration',options.duration))}${group('Evolução',choices('evolution',options.evolution))}${group('Recorrência',choices('recurrence',['Sim','Não'])+textField('recurrenceCount','Quantos?','number'))}${area('painStarted','Como a dor começou?')}<div class="subgroup"><div class="group-title">Intensidade da Dor — EVA 0–10</div>${scale('painCurrent','Dor atual')}${scale('painWorst','Pior (7 dias)')}${scale('painBest','Melhor (7 dias)')}${scale('painAverage','Média (7 dias)')}</div>`],
 [4,'Mapa Corporal',`${group('Localização dos sintomas',`<div class="legend">${BodyMap.symptoms.slice(1).map(item => `<span class="legend-item"><i class="legend-dot" style="background:${item.color}"></i>${item.label}</span>`).join('')}</div><p class="legend" id="body-map-help">Clique ou toque em uma região para alternar: sem marcação → dor → formigamento → queimação → choque → irradiação → sem marcação. Use Tab e Enter ou Espaço no teclado. Para áreas pequenas, use a marcação por região abaixo de cada vista.</p><div class="map">${map('Frente')}${map('Costas')}</div>`)}${group('Lado predominante',choices('dominantSide',options.side))}`],
 [5,'Comportamento dos Sintomas',`<div class="grid grid-3">${group('Tipo de dor',choices('painType',options.painType))}${group('Padrão temporal',choices('temporalPattern',options.temporal,'checkbox'))}${group('Característica',choices('painCharacteristic',options.characteristics,'checkbox'))}</div><div class="grid grid-2">${group('O que piora',choices('worse',options.worse,'checkbox'))}${group('O que melhora',choices('better',options.better,'checkbox'))}</div>`],
 [6,'Triagem de Segurança — Red Flags',`${group('Triagem de Segurança — Red Flags',choices('redFlags',options.redFlags,'checkbox'))}${group('Resultado da triagem',choices('screeningResult',['Sem suspeita','Investigar','Encaminhamento médico']))}`],
 [7,'Crenças, Expectativas e Objetivos',`${area('painBelief','O que você acredita que está causando sua dor?')}${area('fearAvoidance','Existe algo que você evita fazer por medo de piorar?')}${area('concern','O que mais preocupa você em relação à sua coluna?')}<div class="grid grid-2">${area('returnTo','O que gostaria de voltar a fazer?')}${textField('goalTime','Em quanto tempo espera atingir esse objetivo?')}</div>`],
 [8,'STarT Back Screening Tool — Brasil',`<p>Pensando nas duas últimas semanas, assinale sua resposta:</p><div class="table-wrap"><table><thead><tr><th>#</th><th>Item</th><th>Concordo (1)</th><th>Discordo (0)</th></tr></thead><tbody>${startItems.map((x,i)=>`<tr><td>${i+1}${i>3?' *':''}</td><td>${x}</td><td>${choices('start'+(i+1),['Concordo'])}</td><td>${choices('start'+(i+1),['Discordo'])}</td></tr>`).join('')}<tr><td>9 *</td><td>Em geral, quanto a sua dor nas costas o incomodou nas últimas 2 semanas?</td><td colspan="2">${choices('start9',['Muito','Extremamente','Nada','Pouco','Moderadamente'])}</td></tr></tbody></table></div><div class="note" id="start-result">Pontuação total (9 itens): — / 9 · Subescala psicossocial (5–9): — / 5<br>Baixo risco — total ≤ 3 · Médio risco — total ≥ 4, psicossocial ≤ 3 · Alto risco — psicossocial ≥ 4</div><div class="note">* Itens 5–9 compõem a subescala psicossocial (yellow flags). Alto risco psicossocial orienta abordagem centrada em educação em dor e terapia cognitivo-comportamental (Hill et al., Arthritis Rheum 2008).</div>`],
 [9,'Questionário Roland-Morris de Incapacidade',`<p>Quando suas costas doem, você pode encontrar dificuldade em fazer algumas coisas que normalmente faz. Marque apenas as frases que descrevem você hoje.</p><div class="grid grid-2">${roland.map((x,i)=>`<label class="choice check"><input type="checkbox" name="roland[]" value="${i+1}"><span>${i+1}. ${x}</span></label>`).join('')}</div><div class="note" id="roland-result">Escore total: 0 / 24 · Ponto de corte: > 14 = incapacidade grave</div>`],
 [10,'Questionário DN4 — Diagnóstico de Dor Neuropática',dn4()],
 [11,'Exame Físico',physical()],
 [12,'Escala Funcional Específica do Paciente (PSFS)',`<p>Identifique até 3 atividades que você está incapaz de fazer ou tem dificuldade por causa do seu problema. Nota de 0 (incapaz) a 10 (capaz como antes).</p><div class="table-wrap"><table><thead><tr><th>#</th><th>Atividade relatada pelo paciente</th><th>Nota (0–10)</th><th>Data</th></tr></thead><tbody>${[1,2,3].map(n=>`<tr><td>${n}</td><td><input class="input" name="psfs${n}Activity"></td><td><input class="input" type="number" min="0" max="10" name="psfs${n}Score"></td><td><input class="input" type="date" name="psfs${n}Date"></td></tr>`).join('')}</tbody></table></div>`],
 [13,'Discriminação do Mecanismo de Dor Predominante',mechanisms()],
 [14,'Classificação Clínica',classification()],
 [15,'Plano Terapêutico Inicial',`${group('Plano Terapêutico Inicial',choices('treatment',['Educação em dor','Exercícios terapêuticos','Exposição gradual ao movimento','Terapia manual','Treinamento funcional','Programa domiciliar','Treino aeróbio','Eletrotermofototerapia / terapias passivas','Agulhamento a seco','Encaminhamento'],'checkbox'))}${area('observations','Observações')}`],
 [16,'Resumo Clínico',`${area('mainHypothesis','Hipótese principal')}${area('contributingFactors','Principais fatores contribuintes')}${area('initialConduct','Conduta inicial')}`],
 [17,'Referências',`<div class="references">${refs.map(x=>`<p>${x}</p>`).join('')}</div>`]
];
function dn4(){const q=['Queimação','Sensação de frio dolorosa','Choque elétrico','Formigamento','Alfinetada e agulhada','Adormecimento','Coceira','Hipoestesia ao toque','Hipoestesia à picada de agulha','Escovação'];return `<p>Versão Brasileira 1.0. Marque SIM ou NÃO para cada item.</p><div class="table-wrap"><table><thead><tr><th>#</th><th>Descrição</th><th>SIM</th><th>NÃO</th></tr></thead><tbody>${q.map((x,i)=>`<tr><td>${i+1}</td><td>${x}</td><td>${choices('dn'+(i+1),['SIM'])}</td><td>${choices('dn'+(i+1),['NÃO'])}</td></tr>`).join('')}</tbody></table></div><div class="note" id="dn-result">Escore DN4: — / 10 · Classificação: Nociceptiva (&lt; 4) Neuropática(≥ 4)</div>`}
function physical(){return `${group('Movimentos Repetidos / Preferência Direcional (MDT)',`<div class="table-wrap"><table><thead><tr><th>Movimento</th><th>Melhora</th><th>Piora</th><th>Sem efeito</th></tr></thead><tbody>${['Extensão repetida','Flexão repetida','Inclinação lateral repetida'].map((x,i)=>`<tr><td>${x}</td><td>${choices('movement'+i,['Melhora'])}</td><td>${choices('movement'+i,['Piora'])}</td><td>${choices('movement'+i,['Sem efeito'])}</td></tr>`).join('')}</tbody></table></div>${group('Resultado',choices('mdtResult',['Centralização','Periferização','Inconclusivo']))}${group('Preferência',choices('mdtPreference',['Flexão','Extensão','Nenhuma']))}${group('Achados',choices('findings',['Desvio lateral','Movimentos aberrantes'],'checkbox'))}`)}${group('Exame Neurológico Segmentar',neuro())}${group('Testes Neurodinâmicos',tests())}${group('Reprodução do Sintoma Principal',choices('symptomReproduction',['Sim','Não'])+textField('reproducedLocation','Local reproduzido'))}`}
function neuro(){return `<div class="table-wrap"><table><thead><tr><th>Nível</th><th>Força (Miótomo)</th><th>Sensibilidade</th><th>Reflexo</th></tr></thead><tbody>${[['L4','Ext. joelho:','Medial da perna:','Patelar:'],['L5','Dorsiflex./ext. hálux:','Dorso do pé:','—'],['S1','Flex. plantar/eversão:','Lateral do pé:','Aquileu:']].map(r=>`<tr><td>${r[0]}</td><td>${r[1]} ${choices(r[0]+'Force',['N','↓'])}</td><td>${r[2]} ${choices(r[0]+'Sensation',['N','↓'])}</td><td>${r[3]} ${r[3]==='—'?'':choices(r[0]+'Reflex',['N','↓','✗'])}</td></tr>`).join('')}</tbody></table></div>`}
function tests(){return `<div class="table-wrap"><table><thead><tr><th>Teste</th><th>Direito</th><th>Esquerdo</th><th>Observações</th></tr></thead><tbody>${['SLR (Lasègue)','SLR cruzado','Slump test','Teste femoral (prone knee bend)'].map((x,i)=>`<tr><td>${x}</td><td>${choices('test'+i+'Right',['+','−'])}</td><td>${choices('test'+i+'Left',['+','−'])}</td><td><input class="input" name="test${i}Notes"></td></tr>`).join('')}</tbody></table></div>`}
function mechanisms(){const cols=[['Nociceptivo',['Dor localizada (não regional/difusa)','Relação proporcional dor / carga','Provocada por posturas/movimentos específicos','Sem hipersensibilidade generalizada','Sem hipoestesia','Resposta proporcional ao exame','Testes especiais consistentes','DN4 < 4']],['Neuropático',['Distribuição dermatomal / trajeto de nervo','Disestesia (choque, parestesia)','Evidência de lesão/doença do SN','Hipoestesia neuroanatômica','Provocada por carga/compressão neural','DN4 ≥ 4','Déficits sensoriais no exame','Provocação neural positiva']],['Nociplástico',['Dor > 3 meses','Distribuição regional (não discreta)','Não explicada por nociceptivo/neuropático','Alodínia mecânica (toque leve)','Sensibilidade à pressão profunda','Sensibilidade ao calor ou frio','Sensações dolorosas posteriores','Sensibilidade a sons/luz/odores','Distúrbio do sono com despertares','Fadiga / problemas cognitivos']]];return `<p>Baseado em Hodges et al., Clin J Pain 2025 e Kosek et al., PAIN 2021. Marque os achados encontrados.</p><div class="grid grid-3">${cols.map((c,i)=>group(c[0],choices('mechanism'+i,c[1],'checkbox'))).join('')}</div><div class="note">Classificação de dor nociplástica (Kosek et al., PAIN 2021)<br>Possível: Critérios obrigatórios (dor > 3 meses, regional, não explicada) + hipersensibilidade evocada no exame<br>Provável: Todos os anteriores + história de hipersensibilidade + comorbidades (sono, fadiga, cognitivo, sensibilidade sensorial)</div>${textField('csi','CSI (SE APLICADO)','number')}<p class="legend">/ 100 ≥ 40 = possível sensibilização central</p>`}
function classification(){return `${group('Classificação da condição',choices('condition',['Dor lombar primária (CID-11: MG30.02)','Dor radicular','Radiculopatia','Estenose lombar','Dor discogênica provável','Dor facetária provável','Dor sacroilíaca provável','Dor crônica primária / nociplástica'],'checkbox'))}${group('Mecanismo predominante',choices('predominantMechanism',['Nociceptivo mecânico','Neural periférico','Nociplástico','Misto']))}<div class="grid grid-3">${textField('nociceptivePercent','Nociceptivo %','number')}${textField('neuralPercent','Neural %','number')}${textField('nociplasticPercent','Nociplástico %','number')}</div>${group('Classificação Internacional de Funcionalidade (CIF)',`<div class="grid">${textField('cifBody','Funções do corpo (b) — Ex: b280 dor, b710 mobilidade, b730 força, b152 emoções, b134 sono')}${textField('cifStructures','Estruturas do corpo (s) — Ex: s760 tronco, s770 membro inferior, s120 medula e nervos')}${textField('cifActivity','Atividade e participação (d) — Ex: d410 mudar posição, d450 andar, d540 vestir-se, d850 trabalho')}${textField('cifEnvironmental','Fatores ambientais (e) — Ex: e310 família, e580 serviços de saúde, e1101 medicamentos')}</div>`)}`}
content.forEach(([n,t,b])=>{form.insertAdjacentHTML('beforeend',section(n,t,b));nav.insertAdjacentHTML('beforeend',`<a class="${n===1?'active':''}" href="#s${n}">${n}. ${t}</a>`)});
function updateScores(){const start=[...document.querySelectorAll('[name^="start"]:checked')];let total=0,psych=0;start.forEach(x=>{if(x.value==='Concordo'||['Muito','Extremamente'].includes(x.value)){total++;if(+x.name.replace('start','')>=5)psych++}});$('#start-result').innerHTML=`Pontuação total (9 itens): ${start.length?total:'—'} / 9 · Subescala psicossocial (5–9): ${start.length?psych:'—'} / 5<br>Baixo risco — total ≤ 3 · Médio risco — total ≥ 4, psicossocial ≤ 3 · Alto risco — psicossocial ≥ 4`;const r=document.querySelectorAll('[name="roland[]"]:checked').length;$('#roland-result').textContent=`Escore total: ${r} / 24 · Ponto de corte: > 14 = incapacidade grave`;const d=[...document.querySelectorAll('[name^="dn"]:checked')].filter(x=>x.value==='SIM').length;$('#dn-result').textContent=`Escore DN4: ${document.querySelector('[name^="dn"]:checked')?d:'—'} / 10 · Classificação: ${d>=4?'Neuropática(≥ 4)':'Nociceptiva (< 4)'}`}
form.addEventListener('change',()=>{updateScores();const all=[...form.querySelectorAll('input,textarea')].filter(x=>x.type!=='radio'&&x.type!=='checkbox');const filled=all.filter(x=>x.value.trim()).length+form.querySelectorAll('input:checked').length;const percentage=Math.min(100,Math.round(filled/Math.max(1,all.length+30)*100));$('#progress-text').textContent=`${percentage}% preenchido`;$('#progress-bar').style.width=`${percentage}%`});
// Keep SVG, precise-touch controls and the PDF state synchronized through one transition.
document.querySelectorAll('.body-map').forEach(container => {
  const view = container.dataset.view;
  const select = container.querySelector('.region-select');
  const button = container.querySelector('.region-cycle');
  const status = container.querySelector('.region-status');
  const describe = id => {
    const region = BodyMap.regions[view].find(item => item.id === id);
    return `${region.label}: ${BodyMap.symptom(bodyMapState[view][id]).label}`;
  };
  const updateControl = () => {
    button.setAttribute('aria-controls',`${view}-${select.value}`);
    button.setAttribute('aria-label',`${describe(select.value)}. Próximo sintoma`);
    status.textContent = describe(select.value);
  };
  const cycle = id => {
    bodyMapState[view][id] = BodyMap.nextState(bodyMapState[view][id]);
    const part = container.querySelector(`[data-region="${id}"]`);
    part.dataset.state = bodyMapState[view][id];
    part.setAttribute('fill',BodyMap.symptom(bodyMapState[view][id]).color);
    part.setAttribute('aria-label',describe(id));
    part.querySelector('title').textContent = describe(id);
    select.value = id;
    updateControl();
  };
  container.querySelectorAll('.part').forEach(part => {
    part.addEventListener('click',() => cycle(part.dataset.region));
    part.addEventListener('keydown',event => {
      if (event.key !== 'Enter' && event.key !== ' ') return;
      event.preventDefault();
      if (!event.repeat) cycle(part.dataset.region);
    });
  });
  select.addEventListener('change',updateControl);
  button.addEventListener('click',() => cycle(select.value));
  updateControl();
});
const navigationLinks=[...nav.querySelectorAll('a')];content.forEach(([n])=>new IntersectionObserver(entries=>{if(entries[0].isIntersecting)navigationLinks.forEach(link=>link.classList.toggle('active',link.getAttribute('href')===`#s${n}`))},{rootMargin:'-20% 0px -70% 0px'}).observe(document.querySelector(`#s${n}`)));
const sectionsToggle = document.querySelector('#sections-toggle');
const sidebar = document.querySelector('.sidebar');
const sidebarBackdrop = document.querySelector('#sidebar-backdrop');
const setSectionsOpen = (open) => {
  sidebar.classList.toggle('is-open', open);
  sidebarBackdrop.classList.toggle('is-visible', open);
  sectionsToggle.setAttribute('aria-expanded', String(open));
  sectionsToggle.textContent = open ? '✕ Fechar' : '☰ Seções';
};
sectionsToggle.addEventListener('click', () => {
  const open = !sidebar.classList.contains('is-open');
  setSectionsOpen(open);
  if (open) navigationLinks[0]?.focus();
});
navigationLinks.forEach(link => link.addEventListener('click', () => setSectionsOpen(false)));
sidebarBackdrop.addEventListener('click', () => { setSectionsOpen(false); sectionsToggle.focus(); });
document.addEventListener('keydown', event => { if (event.key === 'Escape' && sidebar.classList.contains('is-open')) { setSectionsOpen(false); sectionsToggle.focus(); } });
const desktopMedia = window.matchMedia('(min-width: 1181px)');
const closeDrawerOnDesktop = event => { if (event.matches) setSectionsOpen(false); };
if (desktopMedia.addEventListener) desktopMedia.addEventListener('change', closeDrawerOnDesktop);
else desktopMedia.addListener(closeDrawerOnDesktop);
